name: Delete packages
on:
  workflow_dispatch:
jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with: 
          package-name: 'atlantis'
          package-type: 'container'